### ISSUE TITLE
iPhone 디바이스 상에서 네이버앱이 깔려있을 경우 로그인 불가현상

### ISSUE THREAD

**Issue by kmh339** [yoonjaepark/flutter_naver_login#25]
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

네이버 앱이 깔린 경우 웹뷰가 아닌 앱을 통해 로그인을 시도하는 듯 한데 이 때,

iOS 의 경우 FlutterNaverLogin.logIn() 가 정상적으로 호출되지 않는듯 합니다.

안드로이드와 네이버앱이 깔리지 않은 iOS의 경우는 정상동작 합니다.

테스트환경은 iOS 버전 13.4와 14.1 입니다.

아래는 제가 구현한 코드입니다.

```dart
 Future<void> _naverLogin() async {
    final NaverLoginResult _naverLoginResult = await FlutterNaverLogin.logIn();

    if (_naverLoginResult.status == NaverLoginStatus.loggedIn) {
      final NaverAccountResult account = _naverLoginResult.account;
      final Map<String, dynamic> json = <String, dynamic>{
        'id': account.id ?? '',
        'email': account.email ?? '',
        'name': account.name ?? '',
      };

      final SocialUser _socialUser = SocialUser.fromJson(json);
      final User _user = await _authRepository.socialSignIn('naver', _socialUser);
      if (_user != null) {
        _authBloc.add(UserLoggedIn(user: _user));
      } else {
        log(']-----] _naverLogin [-----[ error ');
      }
    } else {
      log(']-----] _naverLogin [-----[ error ');
    }
  }
```

**Comment by astroshim** [comment]
저도 같은 현상 입니다.
`FlutterNaverLogin.logIn()` 에서 return 이 안되네요.

**Comment by gkssk925** [comment]
저도 같은 현상입니다. 
FlutterNaverLogin.logIn() 에서 return 이 안되고 있습니다.

**Comment by sehoon787** [comment]
저도 동일한 현상입니다.
추가적으로 `await FlutterNaverLogin.isLoggedIn` 또한 해당 상황에서 아래와 같은 에러를 반환합니다.
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: FormatException: Invalid date format
0
#0      DateTime.parse (dart:core/date_time.dart:347:7)
#1      NaverAccessToken.isValid (package:flutter_naver_login/flutter_naver_login.dart:109:52)
#2      FlutterNaverLogin.isLoggedIn (package:flutter_naver_login/flutter_naver_login.dart:32:36)
<asynchronous suspension>
```

**Comment by sehoon787** [comment]
현재 해당 이슈는 아래 xcode 변경 사항으로 인해 AppDelegate.swift 파일에 해당 라인 수정하여 해결 할 수 있습니다.
`Swift Compiler Error (Xcode): 'UIApplicationOpenURLOptionsKey' has been renamed to 'UIApplication.OpenURLOptionsKey'`

```
    override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        var applicationResult = false
        if (!applicationResult) {
           applicationResult = NaverThirdPartyLoginConnection.getSharedInstance().application(app, open: url, options: options)
        }
        // if you use other application url process, please add code here.

        if (!applicationResult) {
           applicationResult = super.application(app, open: url, options: options)
        }
        return applicationResult
    }
```

**Comment by yjs8237** [comment]
음 이 이슈 해결되었나요?

**Comment by evar-leeo** [comment]
`AppDelegate.swift

import Flutter
import UIKit
import NaverThirdPartyLogin

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  
  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    var applicationResult = false
    if (!applicationResult) {
        applicationResult = NaverThirdPartyLoginConnection.getSharedInstance().application(app, open: url, options: options)
    }

    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    }
    
    if (!applicationResult) {
        applicationResult = super.application(app, open: url, options: options)
    }
    return applicationResult
  }
}
  
`

위와 같이 수정하시면 됩니다


Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (5 months ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3
