### ISSUE TITLE
Android에서 갑자기 다음 에러가 뜹니다: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by gracegyu** [yoonjaepark/flutter_naver_login#58]
Flutter v2.10에서 naver login을 접목하고 있습니다.
Android에서 로그인이 잘되었는데, 아래코드 호출하면 갑자기 다음의 에러가 뜹니다.

NaverLoginResult res = await FlutterNaverLogin.logIn();

I/NaverIdLogin|com.mycompay.myapp|OAuthLoginEncryptedPreferenceManager(21114): access token is expired.
E/MethodChannel#flutter_naver_login(21114): Failed to handle method call
E/MethodChannel#flutter_naver_login(21114): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/MethodChannel#flutter_naver_login(21114): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/MethodChannel#flutter_naver_login(21114): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/MethodChannel#flutter_naver_login(21114): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/MethodChannel#flutter_naver_login(21114): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
E/MethodChannel#flutter_naver_login(21114): 	at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:39)
E/MethodChannel#flutter_naver_login(21114): 	at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:32)
E/MethodChannel#flutter_naver_login(21114): 	at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:196)
E/MethodChannel#flutter_naver_login(21114): 	at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:104)
E/MethodChannel#flutter_naver_login(21114): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:193)
E/MethodChannel#flutter_naver_login(21114): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onMethodCall(FlutterNaverLoginPlugin.kt:127)
E/MethodChannel#flutter_naver_login(21114): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter_naver_login(21114): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#flutter_naver_login(21114): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#flutter_naver_login(21114): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#flutter_naver_login(21114): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_naver_login(21114): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_naver_login(21114): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter_naver_login(21114): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter_naver_login(21114): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#flutter_naver_login(21114): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_naver_login(21114): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter_naver_login(21114): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter (21114): error on Naver login: PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null, java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
I/flutter (21114): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
I/flutter (21114): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
I/flutter (21114): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
I/flutter (21114): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
I/flutter (21114): 	at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:39)
I/flutter (21114): 	at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:32)
I/flutter (21114): 	at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:196)
I/flutter (21114): 	at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:104)
I/flutter (21114): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:193)
I/flutter (21114): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onMethodCall(FlutterNaverLoginPlugin.kt:127)
I/flutter (21114): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (21114): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
I/flutter (21114): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
I/flutter (21114): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
I/flutter (21114): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (21114): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (21114): 	at android.os.Looper.loopOnce(Looper.java:201)
I/flutter (21114): 	at android.os.Looper.loop(Looper.java:288)
I/flutter (21114): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
I/flutter (21114): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (21114): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
I/flutter (21114): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter (21114): )

**Comment by syonkr** [comment]
이번 naver login 5.0.1 업데이트 이후로 네이버에서 dialog 등을 AppCompat 으로 모두 변경하면서 생기는 문제입니다.

android/app/src/main/AndroidManifest.xml 에 
```
...

 <activity android:name="com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity"
                  android:theme="@style/LaunchTheme">
```
코드를 추가하신뒤 

android/app/src/main/res/values/styles.xml 에
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
</resources>
```
코드를
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
</resources>
```
로 변경하여주시면됩니다.
(@android:style/Theme.Black.NoTitleBar -> Theme.AppCompat.DayNight.NoActionBar)

관련 코드는 5.0.1 Update Commit에서 확인 가능하시며  수정내용을 반영해주시기 바랍니다.

감사합니다.

**Comment by gracegyu** [comment]
Theme.AppCompat.DayNight.NoActionBar로 설정하면 아래 에러가 납니다.
Theme.AppCompat.Night.NoActionBar로 설정하니 빌드/실행이 되네요. 감사합니다.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:AAPT: error: resource style/Theme.AppCompat.DayLight.NoActionBar (aka com.vatech.cleverpam:style/Theme.AppCompat.DayLight.NoActionBar) not found.
     error: failed linking references.

**Comment by syonkr** [comment]
@gracegyu DayNight가 아닌 DayLight로 쓰신거같긴하지만 ...우선 AppCompat 을 사용하는게 주목적이라 따로 디자인에 문제가 없으시다면 그대로 사용하셔도 될거같습니다.

감사합니다.

**Comment by gracegyu** [comment]
오타을 입력했군요. 확인했습니다. 대단히 감사합니다.

**Comment by Woojin-Crive** [comment]
Flutter 2.10.3 사용중입니다!

android>app>src>main>androidmanifest.xml
       <activity android:name="com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity"
           android:theme="@style/LaunchTheme">
       </activity>
추가했고

android>app>src>main>res>values>styles.xml
<style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
로 변경하였습니다.

또한 라이브러리 버전도 1.3.1로 올렸습니다.
flutter clean & flutter pub get 하였습니다!

E[/MethodChannel]()#flutter_naver_login(31394): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E[/MethodChannel]()#flutter_naver_login(31394): 	at android.os.Handler.handleCallback(Handler.java:883)
E[/MethodChannel]()#flutter_naver_login(31394): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E[/MethodChannel]()#flutter_naver_login(31394): 	at android.os.Looper.loop(Looper.java:237)
E[/MethodChannel]()#flutter_naver_login(31394): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E[/MethodChannel]()#flutter_naver_login(31394): 	at java.lang.reflect.Method.invoke(Native Method)
E[/MethodChannel]()#flutter_naver_login(31394): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E[/MethodChannel]()#flutter_naver_login(31394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E[/flutter]() (31394): [ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null, java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E[/flutter]() (31394): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
E[/flutter]() (31394): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
E[/flutter]() (31394): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
E[/flutter]() (31394): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:94)
E[/flutter]() (31394): 	at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:39)
E[/flutter]() (31394): 	at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:32)
E[/flutter]() (31394): 	at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:196)
E[/flutter]() (31394): 	at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:104)
E[/flutter]() (31394): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:193)
E[/flutter]() (31394): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onMethodCall(FlutterNaverLoginPlugin.kt:127)
E[/flutter]() (31394): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E[/flutter]() (31394): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E[/flutter]() (31394): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E[/flutter]() (31394): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E[/flutter]() (31394): 	at android.os.Handler.handleCallback(Handler.java:883)
E[/flutter]() (31394): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E[/flutter]() (31394): 	at android.os.Looper.loop(Looper.java:237)
E[/flutter]() (31394): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E[/flutter]() (31394): 	at java.lang.reflect.Method.invoke(Native Method)
E[/flutter]() (31394): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E[/flutter]() (31394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E[/flutter]() (31394): )
E[/flutter]() (31394): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E[/flutter]() (31394): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
E[/flutter]() (31394): <asynchronous suspension>
E[/flutter]() (31394): #2      FlutterNaverLogin.logIn
package:flutter_naver_login[/flutter]()_naver_login.dart:11
E/flutter (31394): <asynchronous suspension>

NaverLoginResult res = await FlutterNaverLogin.logIn();
코드를 실행할때 해당 문제가 나타나고 있는데 어떤 부분이 문제일까요..?

**Comment by syonkr** [comment]
@Woojin-Crive 올려주신 내용을 읽기는 힘들지만 동일한 오류로 추정됩니다.
android/app/src/main/AndroidManifest.xml 에 있는 MainActivity 의 theme가 "@style/LaunchTheme"로 되어있는지 확인부탁들비니다.

**Comment by Woojin-Crive** [comment]
최초 로그인시에는 문제가 없는데 다시 로그인하려고 하면 문제가 생깁니다.

이하는 android/app/src/main/AndroidManifest.xml 입니다.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.app.aapp">

    <queries>
        <!-- If your app opens https URLs -->
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>

    </queries>

   <application
       android:label="app"
       android:requestLegacyExternalStorage="true"
       android:exported="true"
       android:icon="@mipmap/ic_launcher">
       <meta-data
           android:name="com.naver.sdk.clientId"
           android:value="@string/client_id" />
       <meta-data
           android:name="com.naver.sdk.clientSecret"
           android:value="@string/client_secret" />
       <meta-data
           android:name="com.naver.sdk.clientName"
           android:value="@string/client_name" />
       <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:exported="true"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity
            android:name="com.navercorp.nid.oauth.NidOAuthBridgeActivity"
            android:exported="true" 
            tools:replace="android:theme"
            android:theme="@style/LaunchTheme"/>

        <activity
            android:name="com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity"
            android:exported="true" 
            tools:replace="android:theme"
            android:theme="@style/LaunchTheme"/>

        <activity
            android:name="com.navercorp.nid.oauth.activity.NidOAuthCustomTabActivity"
            android:exported="true"
            tools:replace="android:theme"
            android:theme="@style/LaunchTheme"/>

        <activity 
          android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
          android:exported="true" 
          android:theme="@style/LaunchTheme"/>

       <meta-data
           android:name="flutterEmbedding"
           android:value="2" />
   </application>
</manifest>
```

이하는 android/app/src/main/res/values/styles.xml 입니다.
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is off -->
    <!-- <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar"> -->
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```

manifest와 style은 AppCompat 테마를 잘 사용하고있는걸로 보이는데 같은 문제가 계속해서 나타나네요..ㅠㅠ

**Comment by Bigstar1108** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDevDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource android:style[/Theme.AppCompat.DayNight.NoActionBar]() not found.
     error: failed linking references.
```

FYI) [해당 코멘트](https://github.com/yoonjaepark/flutter_naver_login/issues/58#issuecomment-1056458373)를 보고 작업할 때 위와같은 오류 혹은 다른 오류가 발생한다면 아래 방법으로 시도해보세요!

1. `com.nhn.android.naverlogin.ui.OAuthCustomTabActivity` 의 theme을 `@style/Theme.AppCompat`으로 설정
2. `com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity` 의 theme을 `@style/Theme.AppCompat`으로 설정
3. `.MainActivity` 의 theme을 `@style/Theme.AppCompat`으로 설정

소스 코드
```
AndroidManifest.xml
...

<application
    android:label="@string/app_name"
    ...>

    <activity 
            android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
            android:exported="true" 
            android:theme="@style/Theme.AppCompat" />

    <activity 
            android:name="com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity"
            android:theme="@style/Theme.AppCompat" />

    ...

    <activity
        android:name=".MainActivity"
        android:theme="@style/Theme.AppCompat"
        ... >
```

혹시나 위 소스코드에 문제가 있으면 코멘트 등록해주세요! : )

**Comment by Heewookji** [comment]
[해당 코멘트](https://github.com/yoonjaepark/flutter_naver_login/issues/58#issuecomment-1056458373)를 보고 작업했는데,
안드로이드 버전 12에서만 해결되지 않아서 
MainActivity의 theme을 @style/Theme.AppCompat로 설정해 해결했습니다.

**Comment by wonpyohong** [comment]
LaunchTheme 내용을 수정하거나 MainActivity에 AppCompat을 적용하면 스플래시 화면에 원치 않는 변경이 생길 수 있어서 LaunchTheme 수정하지 말고, 또한 MainActivity에도 기존 LaunchTheme 그대로 적용하는게 어떨까 싶습니다.

즉, 원래 상태에서 AndroidManifest.xml에 아래 코드만 추가하는 임시 방편을 제안합니다. 그리고 패키지의 AndroidManifest에 추가한다면 모든 사람이 각자의 프로젝트에 넣을 필요 없이 잘 동작할 것 같습니다 (확인 필요)

<activity android:name="com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity"
    android:theme="@style/Theme.AppCompat"
    android:exported="true"
    />

**Comment by byungjuJin** [comment]
이 코드 추가하면 
`<activity android:name="com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity"
                  android:theme="@style/LaunchTheme"/>`

이런 오류가 뜨네요.
```
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute activity#com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity@theme value=(@style/LaunchTheme) from AndroidManifest.xml:70:13-47
  	is also present at [com.navercorp.nid:oauth:5.2.0] AndroidManifest.xml:41:13-75 value=(@style/Theme.AppCompat.Transparent.NoActionBar).
  	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:69:9-70:49 to override.
```

이렇게 . MainActivity 를 수정하면 에러 없고요.
```
<activity
        android:name=".MainActivity"
        android:theme="@style/Theme.AppCompat"
        ... >
```
