### ISSUE TITLE
[ios] appDelegate 수정시 Firebase.initializaApp과 충돌나는 현상이 있습니다

### ISSUE THREAD

**Issue by gamcho3** [yoonjaepark/flutter_naver_login#74]
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:199:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)

*firebase를 주석처리후 실행하면 "MissingPluginException(No implementation found for method logIn on channel flutter_naver_login)"
으로 뜹니다.

**Comment by rambozzang** [comment]
이문제 해결되었나요?
