### ISSUE TITLE
[안드로이드] Failed to handle method call, kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by myeongseop-sofit** [yoonjaepark/flutter_naver_login#77]
아래와 같이 오류가 나는데 왜 그런걸까요?
신규 프로젝트에서도 동일하네요..

Failed to handle method call
E/MethodChannel#flutter_naver_login(30470): kotlin.UninitializedPropertyAccessException: lateinit property launcher has not been initialized
E/MethodChannel#flutter_naver_login(30470): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:212)
E/MethodChannel#flutter_naver_login(30470): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onMethodCall(FlutterNaverLoginPlugin.kt:151)
E/MethodChannel#flutter_naver_login(30470): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter_naver_login(30470): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_naver_login(30470): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_naver_login(30470): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_naver_login(30470): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_naver_login(30470): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_naver_login(30470): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#flutter_naver_login(30470): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#flutter_naver_login(30470): 	at android.app.ActivityThread.main(ActivityThread.java:8855)
E/MethodChannel#flutter_naver_login(30470): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_naver_login(30470): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#flutter_naver_login(30470): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter (30470): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property launcher has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property launcher has not been initialized
E/flutter (30470): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:212)
E/flutter (30470): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onMethodCall(FlutterNaverLoginPlugin.kt:151)
E/flutter (30470): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (30470): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (30470): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (30470): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (30470): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (30470): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (30470): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter (30470): 	at android.os.Looper.loop(Looper.java:313)
E/flutter (30470): 	at android.app.ActivityThread.main(ActivityThread.java:8855)
E/flutter (30470): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30470): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter (30470): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter (30470): )
E/flutter (30470): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (30470): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (30470): <asynchronous suspension>
E/flutter (30470): #2      FlutterNaverLogin.logIn (package:flutter_naver_login/flutter_naver_login.dart:11:39)
E/flutter (30470): <asynchronous suspension>
E/flutter (30470): #3      _MyHomePageState.loginNaver (package:testnaver/main.dart:118:37)
E/flutter (30470): <asynchronous suspension>
E/flutter (30470):

**Comment by hdjeong80** [comment]
어떻게 해결하셨나요? @myeongseop-sofit

**Comment by myeongseop-sofit** [comment]
MainActivity 파일에서

class MainActivity: FlutterFragmentActivity() 

FlutterFragmentActivity로 변경하면 됩니다.
