### ISSUE TITLE
release 빌드에서만 lateinit property launcher has not been initialized, null 에러가 발생합니다.

### ISSUE THREAD

**Issue by kghoon** [yoonjaepark/flutter_naver_login#81]
I/flutter ( 2680): [LoginBloc] PlatformException(error, lateinit property launcher has not been initialized, null, kotlin.x: lateinit property launcher has not been initialized
I/flutter ( 2680): 	at g.n.a.b.d(Unknown Source:24)
I/flutter ( 2680): 	at g.n.a.b.onMethodCall(Unknown Source:20)
I/flutter ( 2680): 	at j.a.d.a.k$a.a(Unknown Source:17)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.e.k(Unknown Source:18)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.e.l(Unknown Source:20)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.e.m(Unknown Source:0)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.c.run(Unknown Source:12)
I/flutter ( 2680): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter ( 2680): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 2680): 	at android.os.Looper.loopOnce(Looper.java:226)
I/flutter ( 2680): 	at android.os.Looper.loop(Looper.java:313)
I/flutter ( 2680): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
I/flutter ( 2680): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 2680): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
I/flutter ( 2680): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/flutter ( 2680): )
I/flutter ( 2680): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
I/flutter ( 2680): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #2      FlutterNaverLogin.logIn (package:flutter_naver_login/flutter_naver_login.dart:11)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #3      NaverUtil.login (package:woodong/src/api/naver_api.dart:23)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #4      LoginBloc.checkUserSignedUp (package:woodong/src/bloc/login/login_bloc.dart:53)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #5      _LoginState.ssoLogin (package:woodong/src/ui/screen/login/login_screen.dart:81)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #6      _LoginState.build.<anonymous closure>.<anonymous closure> (package:woodong/src/ui/screen/login/login_screen.dart:131)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): {code: -401, msg: this access token does not exist}
릴리즈 빌드에서만 발생하는 문제입니다. 'launcher' property 가 준비가 안될걸로 봐서 onAttachedToActivity 가 호출이 안되었거나, 타이밍 문제가 있는 것 같습니다.

**Comment by kghoon** [comment]
버전은 1.2.2 입니다.

**Comment by GwonHyeok** [comment]
안드로이드 디버그 빌드인경우 동일한 문제 발생합니다.

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale ko-KR)
    • Flutter version 3.3.8 on channel stable at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ghyeok/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/ghyeok/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/ghyeok/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/ghyeok/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/ghyeok/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/ghyeok/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ
      IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Users/ghyeok/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4167.29/IntelliJ
      IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • 1EFC09C2-AECF-49A0-854C-349337304BF6 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
