### ISSUE TITLE
login errorPLatformExection on Android.

### ISSUE THREAD

**Issue by farhodyusupov** [yoonjaepark/flutter_naver_login#90]
When I am trying to log in from Android I`m getting this error:

`I/flutter (13874): login errorPlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null, java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
I/flutter (13874): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
I/flutter (13874): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
I/flutter (13874): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
I/flutter (13874): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
I/flutter (13874): 	at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:40)
I/flutter (13874): 	at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:33)
I/flutter (13874): 	at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:199)
I/flutter (13874): 	at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:108)
I/flutter (13874): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:212)
I/flutter (13874): 	at com.yo`

**Comment by nari-nam** [comment]
Same issue for me,
