### ISSUE TITLE
AppCompat exception when trying to login second time.

### ISSUE THREAD

**Issue by nari-nam** [yoonjaepark/flutter_naver_login#95]
AppCompat exception when trying to login second time.

```
PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null, java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
I/flutter (25207): │ 💡         at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
I/flutter (25207): │ 💡         at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
I/flutter (25207): │ 💡         at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
I/flutter (25207): │ 💡         at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
I/flutter (25207): │ 💡         at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:40)
I/flutter (25207): │ 💡         at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:33)
I/flutter (25207): │ 💡         at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:199)
I/flutter (25207): │ 💡         at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:108)
I/flutter (25207): │ 💡         at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.login(FlutterNaverLoginPlugin.kt:212)
I/flutter (25207): │ 💡         at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onMethodCall(FlutterNaverLoginPlugin.kt:151)
I/flutter (25207): │ 💡         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (25207): │ 💡         at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (25207): │ 💡         at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (25207): │ 💡         at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (25207): │ 💡         at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (25207): │ 💡         at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (25207): │ 💡         at android.os.Looper.loopOnce(Looper.java:226)
I/flutter (25207): │ 💡         at android.os.Looper.loop(Looper.java:313)
I/flutter (25207): │ 💡         at android.app.ActivityThread.main(ActivityThread.java:8751)
I/flutter (25207): │ 💡         at java.lang.reflect.Method.invoke(Native Method)
I/flutter (25207): │ 💡         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
I/flutter (25207): │ 💡         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by nari-nam** [comment]
Closed because it is duplicated #58
